### PR TITLE
Use babel for backwards compatibility

### PR DESCRIPTION
**Pull request by LucaT1**
I've got a question. Would you like to test the package alongside linting on the CI builds?
It would check if the babel transpilation affected functionality on older node versions

Theoretically, the babel setup is working, but I'm unable to test it since the licensewatch package hasn't been published with the latest compatibility fixes. That's the error as you can see

screen shot 2017-10-17 at 14 13 10

Also one note:
I've locked the babel dependencies, but i saw you are using all versions with the up to sign(`^`), would you like me to change this?

### CODE REVIEW

**Comment by lirantal** [comment]
Great stuff @LucaT1 

Definitely let's enable linting on the CI too.
And you're right, I didn't yet publish a new npm version for the base package, I need to increment a major version and will push it then.

We can leave the versions with a carrot on the package.json, but regardless of ^ or ~ yarn will lock whatever you install and commit.

**Comment by LucaT1** [comment]
Oh yeah, the yarn locking works anyway but it may create issues for people who use npm or for auto-updating services like greenkeeper. But that's not the topic of this PR so let's move on.

I'll unlock the versions and then it should be ready for review.

**Comment by LucaT1** [comment]
I've unlocked the versions. I saw in the git diff that the yarn resolution has changed. The previous version of the yarn.lock(the one that's currently in master) resolves dependencies from npm's cdn. Do you want to rever it or is it okay to stick with yarn's offering?

**Comment by lirantal** [comment]
I published 2.0.0 for licensewatch. Can you update package.json and yarn's lockfile accordingly so it will also make CI pass?

**Comment by LucaT1** [comment]
Yeah i'll do it right now! 🎉

**Comment by lirantal** [comment]
You're right, check now :)

**Comment by LucaT1** [comment]
Ready to be merged! 🎉

**Comment by lirantal** [comment]
yep, much better now :)

so only thing is about `dist.js` being in gitignore which means it won't be shipped but rather installed on the user's install. It's different than what we do in licensewatch so just change to not ignore and commit it?

**Comment by LucaT1** [comment]
I think you've made a mistake. The behavior you described would happen if I ignored in the `.npmignore`, but I've set it in the gitignore file so any compiled file won't be uploaded to the git repo, although it will be uploaded to npm's CDN.

Anyway, I'll do as you suggested, keeping things similar between the two projects.

**Comment by LucaT1** [comment]
Sorry for the delay. I think it's ready to merge now

/cc @lirantal

**Comment by lirantal** [comment]
Let's  re-iterate the dist.js file for a second - my point was that you should remove it from .gitignore and then commit it to the project. This will ensure that the dist file which the project depends on is always available. Why do I lean to this? because if a project would be installed with `--prod` or `--only=production` type of flags then devDependencies won't be installed and there will be no way to generate the dist.js file on the end user that is installing the package. This is the reason why I followed this exactly in `licensewatch`

However, since licenseye is a top/global package then I agree it doesn't make much sense to install it with the --prod. So final request is to bring back `dist.js` to .gitignore and I'll merge.

Appreciate your patience on this :-)

**Comment by LucaT1** [comment]
Cool. But I'd like to point out that(at least for what I know) the prepublish script will be run upon publishing, and this means that any user who installs the package will anyway get the dist.js file compiled from the machine of the publisher and then uploaded to NPM. This without build steps required. This is how the npm prepbulish script works FWIK. This methodology should apply also to `--prod` flag since the dist file is stored in the npm tarball that the user will download regardless of the contextual ENVs(dev, prod, devOnly, etc...)

Here's the source: https://docs.npmjs.com/misc/scripts#use-cases

To describe my understanding better, this is the process that should happen:

Developer side:
`PUBLISHER -> runs prepublish -> publish to NPM(with the dist file bundled)`

User side:
`USER-> npm i -g licenseye -> downloads the tarball from NPM(contains the dist file as before)`

**Comment by lirantal** [comment]
yep, what we're saying is not conflicting :-)
adding `dist.js` back to .gitignore is only so that after build step the git staging area is clean. Makes sense?

**Comment by lirantal** [comment]
Thanks!
Appreciate your elaborate responses through-out and taking this on 💪

**Pull request merged**
